# coding: utf-8

"""
    API - API Front

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wizipet_api.api.front_group_api import FrontGroupApi


class TestFrontGroupApi(unittest.IsolatedAsyncioTestCase):
    """FrontGroupApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = FrontGroupApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api_v1_front_groups_group_id_patch(self) -> None:
        """Test case for api_v1_front_groups_group_id_patch

        """
        pass

    async def test_api_v1_front_profile_pet_id_groups_get(self) -> None:
        """Test case for api_v1_front_profile_pet_id_groups_get

        """
        pass

    async def test_api_v1_front_profile_pet_id_groups_group_id_abonnement_delete(self) -> None:
        """Test case for api_v1_front_profile_pet_id_groups_group_id_abonnement_delete

        """
        pass

    async def test_api_v1_front_profile_pet_id_groups_group_id_abonnement_put(self) -> None:
        """Test case for api_v1_front_profile_pet_id_groups_group_id_abonnement_put

        """
        pass

    async def test_api_v1_front_profile_pet_id_groups_group_id_get(self) -> None:
        """Test case for api_v1_front_profile_pet_id_groups_group_id_get

        """
        pass

    async def test_api_v1_front_profile_pet_id_groups_post(self) -> None:
        """Test case for api_v1_front_profile_pet_id_groups_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
