# coding: utf-8

"""
    API - API Front

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wizipet_api.api.front_rappel_api import FrontRappelApi


class TestFrontRappelApi(unittest.IsolatedAsyncioTestCase):
    """FrontRappelApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = FrontRappelApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api_v1_front_profile_pet_id_santes_rappels_post(self) -> None:
        """Test case for api_v1_front_profile_pet_id_santes_rappels_post

        """
        pass

    async def test_api_v1_front_profile_pet_id_santes_rappels_rappel_id_delete(self) -> None:
        """Test case for api_v1_front_profile_pet_id_santes_rappels_rappel_id_delete

        """
        pass


if __name__ == '__main__':
    unittest.main()
