# coding: utf-8

"""
    API - API Front

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wizipet_api.api.front_warn_api import FrontWarnApi


class TestFrontWarnApi(unittest.IsolatedAsyncioTestCase):
    """FrontWarnApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = FrontWarnApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api_v1_front_profile_pet_id_warns_get(self) -> None:
        """Test case for api_v1_front_profile_pet_id_warns_get

        """
        pass

    async def test_api_v1_front_profile_pet_id_warns_warn_id_delete(self) -> None:
        """Test case for api_v1_front_profile_pet_id_warns_warn_id_delete

        """
        pass


if __name__ == '__main__':
    unittest.main()
