# coding: utf-8

"""
    API - API Front

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wizipet_api.api.front_discussion_api import FrontDiscussionApi


class TestFrontDiscussionApi(unittest.IsolatedAsyncioTestCase):
    """FrontDiscussionApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = FrontDiscussionApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api_v1_front_profile_pet_id_discussions_discussion_id_get(self) -> None:
        """Test case for api_v1_front_profile_pet_id_discussions_discussion_id_get

        """
        pass

    async def test_api_v1_front_profile_pet_id_discussions_discussion_id_is_archived_put(self) -> None:
        """Test case for api_v1_front_profile_pet_id_discussions_discussion_id_is_archived_put

        """
        pass

    async def test_api_v1_front_profile_pet_id_discussions_discussion_id_messages_get(self) -> None:
        """Test case for api_v1_front_profile_pet_id_discussions_discussion_id_messages_get

        """
        pass

    async def test_api_v1_front_profile_pet_id_discussions_discussion_id_messages_post(self) -> None:
        """Test case for api_v1_front_profile_pet_id_discussions_discussion_id_messages_post

        """
        pass

    async def test_api_v1_front_profile_pet_id_discussions_discussion_id_messages_read_put(self) -> None:
        """Test case for api_v1_front_profile_pet_id_discussions_discussion_id_messages_read_put

        """
        pass

    async def test_api_v1_front_profile_pet_id_discussions_discussion_id_messages_resume_get(self) -> None:
        """Test case for api_v1_front_profile_pet_id_discussions_discussion_id_messages_resume_get

        """
        pass

    async def test_api_v1_front_profile_pet_id_discussions_discussion_id_participants_me_delete(self) -> None:
        """Test case for api_v1_front_profile_pet_id_discussions_discussion_id_participants_me_delete

        """
        pass

    async def test_api_v1_front_profile_pet_id_discussions_discussion_id_patch(self) -> None:
        """Test case for api_v1_front_profile_pet_id_discussions_discussion_id_patch

        """
        pass

    async def test_api_v1_front_profile_pet_id_discussions_get(self) -> None:
        """Test case for api_v1_front_profile_pet_id_discussions_get

        """
        pass

    async def test_api_v1_front_profile_pet_id_discussions_post(self) -> None:
        """Test case for api_v1_front_profile_pet_id_discussions_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
