# coding: utf-8

"""
    API - API Front

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wizipet_api.api.front_publication_api import FrontPublicationApi


class TestFrontPublicationApi(unittest.IsolatedAsyncioTestCase):
    """FrontPublicationApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = FrontPublicationApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api_v1_front_profile_pet_id_groups_publications_get(self) -> None:
        """Test case for api_v1_front_profile_pet_id_groups_publications_get

        """
        pass

    async def test_api_v1_front_profile_pet_id_publications_get(self) -> None:
        """Test case for api_v1_front_profile_pet_id_publications_get

        """
        pass

    async def test_api_v1_front_profile_pet_id_publications_likes_post(self) -> None:
        """Test case for api_v1_front_profile_pet_id_publications_likes_post

        """
        pass

    async def test_api_v1_front_profile_pet_id_publications_post(self) -> None:
        """Test case for api_v1_front_profile_pet_id_publications_post

        """
        pass

    async def test_api_v1_front_profile_pet_id_publications_publication_id_delete(self) -> None:
        """Test case for api_v1_front_profile_pet_id_publications_publication_id_delete

        """
        pass

    async def test_api_v1_front_profile_pet_id_publications_publication_id_get(self) -> None:
        """Test case for api_v1_front_profile_pet_id_publications_publication_id_get

        """
        pass

    async def test_api_v1_front_profile_pet_id_publications_publication_id_like_put(self) -> None:
        """Test case for api_v1_front_profile_pet_id_publications_publication_id_like_put

        """
        pass

    async def test_api_v1_front_profile_pet_id_publications_publication_id_report_post(self) -> None:
        """Test case for api_v1_front_profile_pet_id_publications_publication_id_report_post

        """
        pass

    async def test_api_v1_front_profile_pet_id_publications_publication_id_share_post(self) -> None:
        """Test case for api_v1_front_profile_pet_id_publications_publication_id_share_post

        Déclare qu'un nouveau partage de la publication à eu lieu.
        """
        pass


if __name__ == '__main__':
    unittest.main()
