# coding: utf-8

"""
    API - API Front

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wizipet_api.api.media_api import MediaApi


class TestMediaApi(unittest.IsolatedAsyncioTestCase):
    """MediaApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = MediaApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api_v1_media_image_google_image_reference_get(self) -> None:
        """Test case for api_v1_media_image_google_image_reference_get

        """
        pass

    async def test_api_v1_media_image_image_id_get(self) -> None:
        """Test case for api_v1_media_image_image_id_get

        """
        pass

    async def test_api_v1_media_image_image_id_post(self) -> None:
        """Test case for api_v1_media_image_image_id_post

        """
        pass

    async def test_api_v1_media_image_post(self) -> None:
        """Test case for api_v1_media_image_post

        """
        pass

    async def test_api_v1_media_video_post(self) -> None:
        """Test case for api_v1_media_video_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
