# coding: utf-8

"""
    API - API Front

    Wizipet API - API Front

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from wizipet_api.models.profiles_discussion_participant_dto import ProfilesDiscussionParticipantDto
from typing import Optional, Set
from typing_extensions import Self

class DiscussionsDiscussionDto(BaseModel):
    """
    DiscussionsDiscussionDto
    """ # noqa: E501
    id: Optional[UUID] = None
    name: Optional[StrictStr] = None
    picture_id: Optional[UUID] = None
    participant_list: Optional[List[ProfilesDiscussionParticipantDto]] = None
    creation_date: Optional[datetime] = None
    last_message_date: Optional[datetime] = None
    random_participant: Optional[ProfilesDiscussionParticipantDto] = None
    __properties: ClassVar[List[str]] = ["id", "name", "picture_id", "participant_list", "creation_date", "last_message_date", "random_participant"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiscussionsDiscussionDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in participant_list (list)
        _items = []
        if self.participant_list:
            for _item_participant_list in self.participant_list:
                if _item_participant_list:
                    _items.append(_item_participant_list.to_dict())
            _dict['participant_list'] = _items
        # override the default output from pydantic by calling `to_dict()` of random_participant
        if self.random_participant:
            _dict['random_participant'] = self.random_participant.to_dict()
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if picture_id (nullable) is None
        # and model_fields_set contains the field
        if self.picture_id is None and "picture_id" in self.model_fields_set:
            _dict['picture_id'] = None

        # set to None if participant_list (nullable) is None
        # and model_fields_set contains the field
        if self.participant_list is None and "participant_list" in self.model_fields_set:
            _dict['participant_list'] = None

        # set to None if last_message_date (nullable) is None
        # and model_fields_set contains the field
        if self.last_message_date is None and "last_message_date" in self.model_fields_set:
            _dict['last_message_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiscussionsDiscussionDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in DiscussionsDiscussionDto) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "picture_id": obj.get("picture_id"),
            "participant_list": [ProfilesDiscussionParticipantDto.from_dict(_item) for _item in obj["participant_list"]] if obj.get("participant_list") is not None else None,
            "creation_date": obj.get("creation_date"),
            "last_message_date": obj.get("last_message_date"),
            "random_participant": ProfilesDiscussionParticipantDto.from_dict(obj["random_participant"]) if obj.get("random_participant") is not None else None
        })
        return _obj


