# coding: utf-8

"""
    API - API Front

    Wizipet API - API Front

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from wizipet_api.models.encyclopedies_unified_article_categorie_dto import EncyclopediesUnifiedArticleCategorieDto
from typing import Optional, Set
from typing_extensions import Self

class EncyclopediesFrontArticleDto(BaseModel):
    """
    EncyclopediesFrontArticleDto
    """ # noqa: E501
    id: Optional[UUID] = None
    title: Optional[StrictStr] = None
    categorie: Optional[EncyclopediesUnifiedArticleCategorieDto] = None
    description: Optional[StrictStr] = None
    image_couverture_id: Optional[UUID] = None
    image_couverture_credit: Optional[StrictStr] = None
    like_count: Optional[StrictInt] = None
    comment_count: Optional[StrictInt] = None
    last_edit_date: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "title", "categorie", "description", "image_couverture_id", "image_couverture_credit", "like_count", "comment_count", "last_edit_date"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EncyclopediesFrontArticleDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if image_couverture_credit (nullable) is None
        # and model_fields_set contains the field
        if self.image_couverture_credit is None and "image_couverture_credit" in self.model_fields_set:
            _dict['image_couverture_credit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EncyclopediesFrontArticleDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in EncyclopediesFrontArticleDto) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "categorie": obj.get("categorie"),
            "description": obj.get("description"),
            "image_couverture_id": obj.get("image_couverture_id"),
            "image_couverture_credit": obj.get("image_couverture_credit"),
            "like_count": obj.get("like_count"),
            "comment_count": obj.get("comment_count"),
            "last_edit_date": obj.get("last_edit_date")
        })
        return _obj


