# coding: utf-8

"""
    API - API Front

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from wizipet_api.models.pense_betes_operation_item_dto import PenseBetesOperationItemDto
from wizipet_api.models.pense_betes_pense_bete_type_dto import PenseBetesPenseBeteTypeDto
from wizipet_api.models.pense_betes_sickness_item_dto import PenseBetesSicknessItemDto
from wizipet_api.models.pense_betes_vaccination_item_dto import PenseBetesVaccinationItemDto
from typing import Optional, Set
from typing_extensions import Self

class PenseBetesPenseBeteItemDto(BaseModel):
    """
    PenseBetesPenseBeteItemDto
    """ # noqa: E501
    id: Optional[UUID] = None
    type: Optional[PenseBetesPenseBeteTypeDto] = None
    var_date: Optional[StrictStr] = Field(default=None, alias="date")
    commentaire: Optional[StrictStr] = None
    operation_properties: Optional[PenseBetesOperationItemDto] = None
    sickness_properties: Optional[PenseBetesSicknessItemDto] = None
    vaccination_properties: Optional[PenseBetesVaccinationItemDto] = None
    __properties: ClassVar[List[str]] = ["id", "type", "date", "commentaire", "operation_properties", "sickness_properties", "vaccination_properties"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PenseBetesPenseBeteItemDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of operation_properties
        if self.operation_properties:
            _dict['operation_properties'] = self.operation_properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sickness_properties
        if self.sickness_properties:
            _dict['sickness_properties'] = self.sickness_properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vaccination_properties
        if self.vaccination_properties:
            _dict['vaccination_properties'] = self.vaccination_properties.to_dict()
        # set to None if commentaire (nullable) is None
        # and model_fields_set contains the field
        if self.commentaire is None and "commentaire" in self.model_fields_set:
            _dict['commentaire'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PenseBetesPenseBeteItemDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in PenseBetesPenseBeteItemDto) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "date": obj.get("date"),
            "commentaire": obj.get("commentaire"),
            "operation_properties": PenseBetesOperationItemDto.from_dict(obj["operation_properties"]) if obj.get("operation_properties") is not None else None,
            "sickness_properties": PenseBetesSicknessItemDto.from_dict(obj["sickness_properties"]) if obj.get("sickness_properties") is not None else None,
            "vaccination_properties": PenseBetesVaccinationItemDto.from_dict(obj["vaccination_properties"]) if obj.get("vaccination_properties") is not None else None
        })
        return _obj


