# coding: utf-8

"""
    API - API Front

    Wizipet API - API Front

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PlacesPlaceCategoryDto(str, Enum):
    """
    PlacesPlaceCategoryDto
    """

    """
    allowed enum values
    """
    SANTESOINS = 'SanteSoins'
    ANIMALERIESJARDINERIES = 'AnimaleriesJardineries'
    EDUCATION = 'Education'
    GARDEPROMENADE = 'GardePromenade'
    ELEVAGE = 'Elevage'
    REFUGES = 'Refuges'
    TOILETTEURS = 'Toiletteurs'
    PETFRIENDLY = 'PetFriendly'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PlacesPlaceCategoryDto from a JSON string"""
        return cls(json.loads(json_str))


