# coding: utf-8

"""
    API - API Front

    Wizipet API - API Front

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from wizipet_api.models.cartes_pet_friendly_location_type_dto import CartesPetFriendlyLocationTypeDto
from wizipet_api.models.googles_lat_lng_literal_dto import GooglesLatLngLiteralDto
from wizipet_api.models.places_place_category_dto import PlacesPlaceCategoryDto
from wizipet_api.models.places_place_sub_category_dto import PlacesPlaceSubCategoryDto
from typing import Optional, Set
from typing_extensions import Self

class PlacesExpediaHotelItemDto(BaseModel):
    """
    PlacesExpediaHotelItemDto
    """ # noqa: E501
    url: Optional[StrictStr] = Field(default=None, description="Lien vers le détail de l'hotel")
    image_url: Optional[StrictStr] = Field(default=None, description="Image de preview")
    promotion_text: Optional[StrictStr] = Field(default=None, description="Contenu du badge promotionnel")
    final_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Prix final, réduction déduite")
    currency: Optional[StrictStr] = Field(default=None, description="Euro par défaut (EUR), ignorable atm")
    strike_out_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Prix sans réduction")
    distance_in_km: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Distance en km (à partir du centre de la bounding box)")
    star_rating: Optional[StrictInt] = Field(default=None, description="Classement de 1 à 5 étoiles")
    guest_rating_count: Optional[StrictInt] = Field(default=None, description="Nombre d'avis utilisateurs")
    guest_rating: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Note des utilisateurs hotels.com de 0 à 10")
    type: Optional[CartesPetFriendlyLocationTypeDto] = None
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    location: Optional[GooglesLatLngLiteralDto] = None
    category_list: Optional[List[PlacesPlaceCategoryDto]] = None
    sub_category_list: Optional[List[PlacesPlaceSubCategoryDto]] = None
    __properties: ClassVar[List[str]] = ["url", "image_url", "promotion_text", "final_price", "currency", "strike_out_price", "distance_in_km", "star_rating", "guest_rating_count", "guest_rating", "type", "id", "name", "location", "category_list", "sub_category_list"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlacesExpediaHotelItemDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if image_url (nullable) is None
        # and model_fields_set contains the field
        if self.image_url is None and "image_url" in self.model_fields_set:
            _dict['image_url'] = None

        # set to None if promotion_text (nullable) is None
        # and model_fields_set contains the field
        if self.promotion_text is None and "promotion_text" in self.model_fields_set:
            _dict['promotion_text'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if strike_out_price (nullable) is None
        # and model_fields_set contains the field
        if self.strike_out_price is None and "strike_out_price" in self.model_fields_set:
            _dict['strike_out_price'] = None

        # set to None if star_rating (nullable) is None
        # and model_fields_set contains the field
        if self.star_rating is None and "star_rating" in self.model_fields_set:
            _dict['star_rating'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if category_list (nullable) is None
        # and model_fields_set contains the field
        if self.category_list is None and "category_list" in self.model_fields_set:
            _dict['category_list'] = None

        # set to None if sub_category_list (nullable) is None
        # and model_fields_set contains the field
        if self.sub_category_list is None and "sub_category_list" in self.model_fields_set:
            _dict['sub_category_list'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlacesExpediaHotelItemDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in PlacesExpediaHotelItemDto) in the input: " + _key)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "image_url": obj.get("image_url"),
            "promotion_text": obj.get("promotion_text"),
            "final_price": obj.get("final_price"),
            "currency": obj.get("currency"),
            "strike_out_price": obj.get("strike_out_price"),
            "distance_in_km": obj.get("distance_in_km"),
            "star_rating": obj.get("star_rating"),
            "guest_rating_count": obj.get("guest_rating_count"),
            "guest_rating": obj.get("guest_rating"),
            "type": obj.get("type"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "location": GooglesLatLngLiteralDto.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "category_list": obj.get("category_list"),
            "sub_category_list": obj.get("sub_category_list")
        })
        return _obj


