# coding: utf-8

"""
    API - API Front

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from wizipet_api.models.contacts_connection_status_dto import ContactsConnectionStatusDto
from wizipet_api.models.groups_pet_summary_dto import GroupsPetSummaryDto
from wizipet_api.models.profiles_alerte_perte_dto import ProfilesAlertePerteDto
from typing import Optional, Set
from typing_extensions import Self

class ProfilesOtherProfileItemDto(BaseModel):
    """
    ProfilesOtherProfileItemDto
    """ # noqa: E501
    id: Optional[UUID] = None
    pet_name: Optional[StrictStr] = None
    picture_id: Optional[UUID] = None
    race_id: Optional[UUID] = None
    ville: Optional[StrictStr] = None
    connection_status: Optional[ContactsConnectionStatusDto] = None
    common_friend_list_overview: Optional[List[GroupsPetSummaryDto]] = None
    common_friend_count: Optional[StrictInt] = None
    alerte_perte: Optional[ProfilesAlertePerteDto] = None
    __properties: ClassVar[List[str]] = ["id", "pet_name", "picture_id", "race_id", "ville", "connection_status", "common_friend_list_overview", "common_friend_count", "alerte_perte"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProfilesOtherProfileItemDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in common_friend_list_overview (list)
        _items = []
        if self.common_friend_list_overview:
            for _item_common_friend_list_overview in self.common_friend_list_overview:
                if _item_common_friend_list_overview:
                    _items.append(_item_common_friend_list_overview.to_dict())
            _dict['common_friend_list_overview'] = _items
        # override the default output from pydantic by calling `to_dict()` of alerte_perte
        if self.alerte_perte:
            _dict['alerte_perte'] = self.alerte_perte.to_dict()
        # set to None if pet_name (nullable) is None
        # and model_fields_set contains the field
        if self.pet_name is None and "pet_name" in self.model_fields_set:
            _dict['pet_name'] = None

        # set to None if picture_id (nullable) is None
        # and model_fields_set contains the field
        if self.picture_id is None and "picture_id" in self.model_fields_set:
            _dict['picture_id'] = None

        # set to None if ville (nullable) is None
        # and model_fields_set contains the field
        if self.ville is None and "ville" in self.model_fields_set:
            _dict['ville'] = None

        # set to None if common_friend_list_overview (nullable) is None
        # and model_fields_set contains the field
        if self.common_friend_list_overview is None and "common_friend_list_overview" in self.model_fields_set:
            _dict['common_friend_list_overview'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProfilesOtherProfileItemDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in ProfilesOtherProfileItemDto) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "pet_name": obj.get("pet_name"),
            "picture_id": obj.get("picture_id"),
            "race_id": obj.get("race_id"),
            "ville": obj.get("ville"),
            "connection_status": obj.get("connection_status"),
            "common_friend_list_overview": [GroupsPetSummaryDto.from_dict(_item) for _item in obj["common_friend_list_overview"]] if obj.get("common_friend_list_overview") is not None else None,
            "common_friend_count": obj.get("common_friend_count"),
            "alerte_perte": ProfilesAlertePerteDto.from_dict(obj["alerte_perte"]) if obj.get("alerte_perte") is not None else None
        })
        return _obj


