# coding: utf-8

"""
    API - API Front

    Wizipet API - API Front

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProfilesEspeceDto(str, Enum):
    """
    ProfilesEspeceDto
    """

    """
    allowed enum values
    """
    CAT = 'Cat'
    DOG = 'Dog'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProfilesEspeceDto from a JSON string"""
        return cls(json.loads(json_str))


