# coding: utf-8

"""
    API - API Front

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from wizipet_api.models.googles_lat_lng_literal_dto import GooglesLatLngLiteralDto
from typing import Optional, Set
from typing_extensions import Self

class PromenadesPostPromenadeDto(BaseModel):
    """
    PromenadesPostPromenadeDto
    """ # noqa: E501
    title: Optional[StrictStr] = None
    promenade_path: Optional[List[GooglesLatLngLiteralDto]] = None
    start_time: Optional[datetime] = None
    duration: Optional[StrictStr] = None
    distance_in_km: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["title", "promenade_path", "start_time", "duration", "distance_in_km"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PromenadesPostPromenadeDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in promenade_path (list)
        _items = []
        if self.promenade_path:
            for _item_promenade_path in self.promenade_path:
                if _item_promenade_path:
                    _items.append(_item_promenade_path.to_dict())
            _dict['promenade_path'] = _items
        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if promenade_path (nullable) is None
        # and model_fields_set contains the field
        if self.promenade_path is None and "promenade_path" in self.model_fields_set:
            _dict['promenade_path'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PromenadesPostPromenadeDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in PromenadesPostPromenadeDto) in the input: " + _key)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "promenade_path": [GooglesLatLngLiteralDto.from_dict(_item) for _item in obj["promenade_path"]] if obj.get("promenade_path") is not None else None,
            "start_time": obj.get("start_time"),
            "duration": obj.get("duration"),
            "distance_in_km": obj.get("distance_in_km")
        })
        return _obj


