# coding: utf-8

"""
    API - API Front

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SantesDureeMoySessionDto(str, Enum):
    """
    SantesDureeMoySessionDto
    """

    """
    allowed enum values
    """
    MINUTES10 = 'Minutes10'
    MINUTES20 = 'Minutes20'
    MINUTES30 = 'Minutes30'
    MINUTES45 = 'Minutes45'
    MINUTES60 = 'Minutes60'
    PLUSDE60MINUTES = 'PlusDe60Minutes'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SantesDureeMoySessionDto from a JSON string"""
        return cls(json.loads(json_str))


