# coding: utf-8

"""
    API - API Front

    Wizipet API - API Front

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class SantesMedicamentationItemDto(BaseModel):
    """
    SantesMedicamentationItemDto
    """ # noqa: E501
    id: Optional[UUID] = None
    var_date: Optional[StrictStr] = Field(default=None, alias="date")
    commentaire: Optional[StrictStr] = None
    antiparasitaire_id: Optional[UUID] = None
    vermifuge_id: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["id", "date", "commentaire", "antiparasitaire_id", "vermifuge_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SantesMedicamentationItemDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if commentaire (nullable) is None
        # and model_fields_set contains the field
        if self.commentaire is None and "commentaire" in self.model_fields_set:
            _dict['commentaire'] = None

        # set to None if antiparasitaire_id (nullable) is None
        # and model_fields_set contains the field
        if self.antiparasitaire_id is None and "antiparasitaire_id" in self.model_fields_set:
            _dict['antiparasitaire_id'] = None

        # set to None if vermifuge_id (nullable) is None
        # and model_fields_set contains the field
        if self.vermifuge_id is None and "vermifuge_id" in self.model_fields_set:
            _dict['vermifuge_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SantesMedicamentationItemDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in SantesMedicamentationItemDto) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "date": obj.get("date"),
            "commentaire": obj.get("commentaire"),
            "antiparasitaire_id": obj.get("antiparasitaire_id"),
            "vermifuge_id": obj.get("vermifuge_id")
        })
        return _obj


