# coding: utf-8

"""
    API - API Front

    Wizipet API - API Front

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from wizipet_api.models.santes_aliment_type_dto import SantesAlimentTypeDto
from wizipet_api.models.santes_set_aliment_catalogue_properties_dto import SantesSetAlimentCataloguePropertiesDto
from wizipet_api.models.santes_set_aliment_custom_properties_dto import SantesSetAlimentCustomPropertiesDto
from typing import Optional, Set
from typing_extensions import Self

class SantesSetAlimentDto(BaseModel):
    """
    SantesSetAlimentDto
    """ # noqa: E501
    type: Optional[SantesAlimentTypeDto] = None
    custom_properties: Optional[SantesSetAlimentCustomPropertiesDto] = None
    catalogue_properties: Optional[SantesSetAlimentCataloguePropertiesDto] = None
    __properties: ClassVar[List[str]] = ["type", "custom_properties", "catalogue_properties"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SantesSetAlimentDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of custom_properties
        if self.custom_properties:
            _dict['custom_properties'] = self.custom_properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of catalogue_properties
        if self.catalogue_properties:
            _dict['catalogue_properties'] = self.catalogue_properties.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SantesSetAlimentDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in SantesSetAlimentDto) in the input: " + _key)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "custom_properties": SantesSetAlimentCustomPropertiesDto.from_dict(obj["custom_properties"]) if obj.get("custom_properties") is not None else None,
            "catalogue_properties": SantesSetAlimentCataloguePropertiesDto.from_dict(obj["catalogue_properties"]) if obj.get("catalogue_properties") is not None else None
        })
        return _obj


