# coding: utf-8

"""
    API - API Front

    Wizipet API - API Front

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SantesClefInfoDto(str, Enum):
    """
    SantesClefInfoDto
    """

    """
    allowed enum values
    """
    BOOLESTSTERILISE = 'BoolEstSterilise'
    BOOLESTGESTANTE = 'BoolEstGestante'
    BOOLESTALLAITANTE = 'BoolEstAllaitante'
    DATEMISEBAS = 'DateMiseBas'
    INTPOIDSGRAMME = 'IntPoidsGramme'
    INTPOIDSFORMEGRAMME = 'IntPoidsFormeGramme'
    ALIMENTRATIONPRINCIPAL = 'AlimentRationPrincipal'
    INTRATIONPRINCIPALGRAMMETOTAL = 'IntRationPrincipalGrammeTotal'
    ENUMRATIONPRINCIPALNOMBREREPAS = 'EnumRationPrincipalNombreRepas'
    BOOLHAVERATIONSECONDAIRE = 'BoolHaveRationSecondaire'
    ALIMENTRATIONSECONDAIRE = 'AlimentRationSecondaire'
    INTRATIONSECONDAIREGRAMMETOTAL = 'IntRationSecondaireGrammeTotal'
    ENUMRATIONSECONDAIRENOMBREREPAS = 'EnumRationSecondaireNombreRepas'
    ENUMQTEFRIANDISE = 'EnumQteFriandise'
    ENUMQTESESSIONJOUR = 'EnumQteSessionJour'
    ENUMDUREEMOYSESSION = 'EnumDureeMoySession'
    INTNIVEAUACTIVITE = 'IntNiveauActivite'
    BOOLACCESEXTERIEUR = 'BoolAccesExterieur'
    BOOLESTCALME = 'BoolEstCalme'
    REFERENCELISTMALADIE = 'ReferenceListMaladie'
    REFERENCELISTSENSIBILITE = 'ReferenceListSensibilite'
    INTALIMENTGRAMME = 'IntAlimentGramme'
    INTACTIVITEMINUTE = 'IntActiviteMinute'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SantesClefInfoDto from a JSON string"""
        return cls(json.loads(json_str))


