# coding: utf-8

"""
    API - API Front

    Wizipet API - API Front

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from wizipet_api.models.santes_pathologie_type_dto import SantesPathologieTypeDto
from typing import Optional, Set
from typing_extensions import Self

class SantesPathologieDto(BaseModel):
    """
    SantesPathologieDto
    """ # noqa: E501
    id: Optional[UUID] = None
    affects_dogs: Optional[StrictBool] = None
    affects_cats: Optional[StrictBool] = None
    name: Optional[StrictStr] = None
    is_pinned: Optional[StrictBool] = None
    type: Optional[SantesPathologieTypeDto] = None
    is_frequent: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "affects_dogs", "affects_cats", "name", "is_pinned", "type", "is_frequent"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SantesPathologieDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SantesPathologieDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in SantesPathologieDto) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "affects_dogs": obj.get("affects_dogs"),
            "affects_cats": obj.get("affects_cats"),
            "name": obj.get("name"),
            "is_pinned": obj.get("is_pinned"),
            "type": obj.get("type"),
            "is_frequent": obj.get("is_frequent")
        })
        return _obj


