# coding: utf-8

"""
    API - API Front

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SantesCoachingStateDto(str, Enum):
    """
    SantesCoachingStateDto
    """

    """
    allowed enum values
    """
    WARNING = 'Warning'
    BRAVO = 'Bravo'
    JUSTSTARTED = 'JustStarted'
    ENDEDBRAVO = 'EndedBravo'
    ENDEDFAILED = 'EndedFailed'
    ENDEDMISSINGWEIGHT = 'EndedMissingWeight'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SantesCoachingStateDto from a JSON string"""
        return cls(json.loads(json_str))


