# coding: utf-8

"""
    API - API Front

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from wizipet_api.models.vaccins_vaccin_dto import VaccinsVaccinDto
from typing import Optional, Set
from typing_extensions import Self

class VaccinsListVaccinDto(BaseModel):
    """
    VaccinsListVaccinDto
    """ # noqa: E501
    vaccin_list: Optional[List[VaccinsVaccinDto]] = None
    __properties: ClassVar[List[str]] = ["vaccin_list"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VaccinsListVaccinDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in vaccin_list (list)
        _items = []
        if self.vaccin_list:
            for _item_vaccin_list in self.vaccin_list:
                if _item_vaccin_list:
                    _items.append(_item_vaccin_list.to_dict())
            _dict['vaccin_list'] = _items
        # set to None if vaccin_list (nullable) is None
        # and model_fields_set contains the field
        if self.vaccin_list is None and "vaccin_list" in self.model_fields_set:
            _dict['vaccin_list'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VaccinsListVaccinDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in VaccinsListVaccinDto) in the input: " + _key)

        _obj = cls.model_validate({
            "vaccin_list": [VaccinsVaccinDto.from_dict(_item) for _item in obj["vaccin_list"]] if obj.get("vaccin_list") is not None else None
        })
        return _obj


